repoUrl: https://github.com/philwelz/argocd.git

applications:

  - name: ingress-nginx
    namespace: ingress-nginx

  - name: cert-manager
    namespace: cert-manager
    ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        # optional: restrict to one specific webhook config
        # name: my-webhook-config
        jqPathExpressions:
        - '.webhooks[].namespaceSelector.matchExpressions'