---
# Source: https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
ingress-nginx:
  controller:
    defaultBackend:
      enabled: true
    replicaCount: 2
    service:
      type: LoadBalancer
      annotations: service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path="/healthz"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true